export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILES_REQUEST = "GET_PROFILES_REQUEST";
export const CLEAR_PROFILE_REQUEST = "CLEAR_PROFILE_REQUEST";
export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
